{
	"perPageNum": 15,
	"currPage": 1,
	"beginNum": 1,
	"endNum": 9,
	"totals": 9,
	"currRecordNum": 9,
	"allPage": 1,
	"rows": [{
		"recordId": 23,
		"rftpBossTime": 0,
		"rftpUpTime": 300,
		"remotePwd": " ",
		"dbUser": " ",
		"remarks": "~!@#$%^&*()_+{}|:\"<>?[]\\;',./",
		"msisdnSender": "interName,interComType,remoteFtpIp,remoteFtpPort,remoteFtpUser,remoteFtpPasv,interVerType,serviceType,remarks,remoteFtpUpPath,rftpUpPathBak,rftpUpPrefix,rftpUpTime,backupKeepDays,active",
		"msisdnReceiptor": " ",
		"interComType": 1,
		"response": 0,
		"rftpBackTime": 0,
		"rftpOperPrefix": " ",
		"rftpBackPath": " ",
		"remoteFtpPwd": "6666",
		"dbName": "",
		"remoteIp": " ",
		"rftpOperTime": 0,
		"rftpBackPathBak": " ",
		"rftpUpPrefix": "MONLOG",
		"remoteName": " ",
		"localPort": 0,
		"dbType": -1,
		"remoteFtpUpPath": "/a/b/c/d1/",
		"localIp": " ",
		"dbPsw": " ",
		"commonCfg": null,
		"interVerType": 6,
		"remoteFtpUser": "666",
		"rftpRemoteBlkPath": "",
		"rftpUpPathBak": "/a/b/c/d2/",
		"ftpDelBackTime": 0,
		"interType": 0,
		"interName": "~!@#$%^&*()_+{}|:\"<>?[]\\;',./",
		"serviceType": "1,2,3",
		"backupKeepDays": 1,
		"syncDirection": 0,
		"remoteFtpIp": "6.6.6.6",
		"remoteFtpPasv": 1,
		"rftpBackPrefix": " ",
		"rftpOperPath": " ",
		"rftpOperPathBak": " ",
		"rftpOperSeqence": 0,
		"rftpUpSeqence": 0,
		"active": 1,
		"remotePort": 0,
		"neBlkCycle": 0,
		"rftpUpPathTmp": "",
		"remoteFtpPort": 21
	},
	{
		"recordId": 45,
		"rftpBossTime": 0,
		"rftpUpTime": 300,
		"remotePwd": " ",
		"dbUser": " ",
		"remarks": "",
		"msisdnSender": "interName,interComType,remoteFtpIp,remoteFtpPort,remoteFtpUser,remoteFtpPasv,interVerType,serviceType,remarks,remoteFtpUpPath,rftpUpPathBak,rftpUpPrefix,rftpUpTime,backupKeepDays,active",
		"msisdnReceiptor": " ",
		"interComType": 1,
		"response": 0,
		"rftpBackTime": 0,
		"rftpOperPrefix": " ",
		"rftpBackPath": " ",
		"remoteFtpPwd": "234",
		"dbName": "",
		"remoteIp": " ",
		"rftpOperTime": 0,
		"rftpBackPathBak": " ",
		"rftpUpPrefix": "MONLOG",
		"remoteName": " ",
		"localPort": 0,
		"dbType": -1,
		"remoteFtpUpPath": "",
		"localIp": " ",
		"dbPsw": " ",
		"commonCfg": null,
		"interVerType": 6,
		"remoteFtpUser": "123",
		"rftpRemoteBlkPath": "",
		"rftpUpPathBak": "",
		"ftpDelBackTime": 0,
		"interType": 0,
		"interName": "1222",
		"serviceType": "4",
		"backupKeepDays": 1,
		"syncDirection": 0,
		"remoteFtpIp": "1.1.1.13",
		"remoteFtpPasv": 1,
		"rftpBackPrefix": " ",
		"rftpOperPath": " ",
		"rftpOperPathBak": " ",
		"rftpOperSeqence": 0,
		"rftpUpSeqence": 0,
		"active": 1,
		"remotePort": 0,
		"neBlkCycle": 0,
		"rftpUpPathTmp": "",
		"remoteFtpPort": 21
	},
	{
		"recordId": 22,
		"rftpBossTime": 0,
		"rftpUpTime": 300,
		"remotePwd": " ",
		"dbUser": " ",
		"remarks": "",
		"msisdnSender": "interName,interComType,remoteFtpIp,remoteFtpPort,remoteFtpUser,remoteFtpPasv,interVerType,serviceType,remarks,remoteFtpUpPath,rftpUpPathBak,rftpUpPrefix,rftpUpTime,backupKeepDays,active",
		"msisdnReceiptor": " ",
		"interComType": 1,
		"response": 0,
		"rftpBackTime": 0,
		"rftpOperPrefix": " ",
		"rftpBackPath": " ",
		"remoteFtpPwd": "11",
		"dbName": "",
		"remoteIp": " ",
		"rftpOperTime": 0,
		"rftpBackPathBak": " ",
		"rftpUpPrefix": "MONLOG",
		"remoteName": " ",
		"localPort": 0,
		"dbType": -1,
		"remoteFtpUpPath": "",
		"localIp": " ",
		"dbPsw": " ",
		"commonCfg": null,
		"interVerType": 6,
		"remoteFtpUser": "test1",
		"rftpRemoteBlkPath": "",
		"rftpUpPathBak": "",
		"ftpDelBackTime": 0,
		"interType": 0,
		"interName": "test1",
		"serviceType": "1",
		"backupKeepDays": 1,
		"syncDirection": 0,
		"remoteFtpIp": "192.168.100.127",
		"remoteFtpPasv": 1,
		"rftpBackPrefix": " ",
		"rftpOperPath": " ",
		"rftpOperPathBak": " ",
		"rftpOperSeqence": 0,
		"rftpUpSeqence": 0,
		"active": 1,
		"remotePort": 0,
		"neBlkCycle": 0,
		"rftpUpPathTmp": "",
		"remoteFtpPort": 21
	},
	{
		"recordId": 41,
		"rftpBossTime": 0,
		"rftpUpTime": 300,
		"remotePwd": " ",
		"dbUser": " ",
		"remarks": "",
		"msisdnSender": "interName,interComType,remoteFtpIp,remoteFtpPort,remoteFtpUser,remoteFtpPasv,interVerType,serviceType,remarks,remoteFtpUpPath,rftpUpPathBak,rftpUpPrefix,rftpUpTime,backupKeepDays,active",
		"msisdnReceiptor": " ",
		"interComType": 1,
		"response": 0,
		"rftpBackTime": 0,
		"rftpOperPrefix": " ",
		"rftpBackPath": " ",
		"remoteFtpPwd": "12312",
		"dbName": "",
		"remoteIp": " ",
		"rftpOperTime": 0,
		"rftpBackPathBak": " ",
		"rftpUpPrefix": "MONLOG",
		"remoteName": " ",
		"localPort": 0,
		"dbType": -1,
		"remoteFtpUpPath": "",
		"localIp": " ",
		"dbPsw": " ",
		"commonCfg": null,
		"interVerType": 6,
		"remoteFtpUser": "123",
		"rftpRemoteBlkPath": "",
		"rftpUpPathBak": "",
		"ftpDelBackTime": 0,
		"interType": 0,
		"interName": "111",
		"serviceType": "3",
		"backupKeepDays": 1,
		"syncDirection": 0,
		"remoteFtpIp": "192.168.10.10",
		"remoteFtpPasv": 1,
		"rftpBackPrefix": " ",
		"rftpOperPath": " ",
		"rftpOperPathBak": " ",
		"rftpOperSeqence": 0,
		"rftpUpSeqence": 0,
		"active": 1,
		"remotePort": 0,
		"neBlkCycle": 0,
		"rftpUpPathTmp": "",
		"remoteFtpPort": 21
	},
	{
		"recordId": 43,
		"rftpBossTime": 0,
		"rftpUpTime": 300,
		"remotePwd": " ",
		"dbUser": " ",
		"remarks": "",
		"msisdnSender": "interName,interComType,remoteFtpIp,remoteFtpPort,remoteFtpUser,remoteFtpPasv,interVerType,serviceType,remarks,remoteFtpUpPath,rftpUpPathBak,rftpUpPrefix,rftpUpTime,backupKeepDays,active",
		"msisdnReceiptor": " ",
		"interComType": 1,
		"response": 0,
		"rftpBackTime": 0,
		"rftpOperPrefix": " ",
		"rftpBackPath": " ",
		"remoteFtpPwd": "123",
		"dbName": "",
		"remoteIp": " ",
		"rftpOperTime": 0,
		"rftpBackPathBak": " ",
		"rftpUpPrefix": "MONLOG",
		"remoteName": " ",
		"localPort": 0,
		"dbType": -1,
		"remoteFtpUpPath": "",
		"localIp": " ",
		"dbPsw": " ",
		"commonCfg": null,
		"interVerType": 6,
		"remoteFtpUser": "123",
		"rftpRemoteBlkPath": "",
		"rftpUpPathBak": "",
		"ftpDelBackTime": 0,
		"interType": 0,
		"interName": "1111",
		"serviceType": "2",
		"backupKeepDays": 1,
		"syncDirection": 0,
		"remoteFtpIp": "192.138.2.2",
		"remoteFtpPasv": 1,
		"rftpBackPrefix": " ",
		"rftpOperPath": " ",
		"rftpOperPathBak": " ",
		"rftpOperSeqence": 0,
		"rftpUpSeqence": 0,
		"active": 1,
		"remotePort": 0,
		"neBlkCycle": 0,
		"rftpUpPathTmp": "",
		"remoteFtpPort": 21
	},
	{
		"recordId": 15,
		"rftpBossTime": 0,
		"rftpUpTime": 300,
		"remotePwd": " ",
		"dbUser": "111111",
		"remarks": "",
		"msisdnSender": "interName,interComType,remoteFtpIp,remoteFtpUser,dbType,interVerType,serviceType,remarks,active",
		"msisdnReceiptor": " ",
		"interComType": 2,
		"response": 0,
		"rftpBackTime": 0,
		"rftpOperPrefix": " ",
		"rftpBackPath": " ",
		"remoteFtpPwd": "111111",
		"dbName": "111111",
		"remoteIp": "192.168.100.127",
		"rftpOperTime": 0,
		"rftpBackPathBak": " ",
		"rftpUpPrefix": "MONLOG",
		"remoteName": " ",
		"localPort": 0,
		"dbType": 0,
		"remoteFtpUpPath": "",
		"localIp": " ",
		"dbPsw": "111111",
		"commonCfg": null,
		"interVerType": 16,
		"remoteFtpUser": "111111",
		"rftpRemoteBlkPath": "",
		"rftpUpPathBak": "",
		"ftpDelBackTime": 0,
		"interType": 0,
		"interName": "<%=½Ó¿ÚÃû³Æ%>",
		"serviceType": "1,2",
		"backupKeepDays": 1,
		"syncDirection": 0,
		"remoteFtpIp": "192.168.100.127",
		"remoteFtpPasv": 1,
		"rftpBackPrefix": " ",
		"rftpOperPath": " ",
		"rftpOperPathBak": " ",
		"rftpOperSeqence": 0,
		"rftpUpSeqence": 0,
		"active": 1,
		"remotePort": 0,
		"neBlkCycle": 0,
		"rftpUpPathTmp": "",
		"remoteFtpPort": 0
	},
	{
		"recordId": 46,
		"rftpBossTime": 0,
		"rftpUpTime": 300,
		"remotePwd": " ",
		"dbUser": " ",
		"remarks": "",
		"msisdnSender": "interName,interComType,remoteFtpIp,remoteFtpPort,remoteFtpUser,remoteFtpPasv,interVerType,serviceType,remarks,remoteFtpUpPath,rftpUpPathBak,rftpUpPrefix,rftpUpTime,backupKeepDays,active",
		"msisdnReceiptor": " ",
		"interComType": 1,
		"response": 0,
		"rftpBackTime": 0,
		"rftpOperPrefix": " ",
		"rftpBackPath": " ",
		"remoteFtpPwd": "aaa",
		"dbName": "",
		"remoteIp": " ",
		"rftpOperTime": 0,
		"rftpBackPathBak": " ",
		"rftpUpPrefix": "MONLOG",
		"remoteName": " ",
		"localPort": 0,
		"dbType": -1,
		"remoteFtpUpPath": "",
		"localIp": " ",
		"dbPsw": " ",
		"commonCfg": null,
		"interVerType": 6,
		"remoteFtpUser": "aaa",
		"rftpRemoteBlkPath": "",
		"rftpUpPathBak": "",
		"ftpDelBackTime": 0,
		"interType": 0,
		"interName": "1",
		"serviceType": "2",
		"backupKeepDays": 1,
		"syncDirection": 0,
		"remoteFtpIp": "1.1.1.2",
		"remoteFtpPasv": 1,
		"rftpBackPrefix": " ",
		"rftpOperPath": " ",
		"rftpOperPathBak": " ",
		"rftpOperSeqence": 0,
		"rftpUpSeqence": 0,
		"active": 1,
		"remotePort": 0,
		"neBlkCycle": 0,
		"rftpUpPathTmp": "",
		"remoteFtpPort": 21
	},
	{
		"recordId": 21,
		"rftpBossTime": 0,
		"rftpUpTime": 300,
		"remotePwd": " ",
		"dbUser": " ",
		"remarks": "",
		"msisdnSender": "interName,interComType,remoteFtpIp,remoteFtpPort,remoteFtpUser,remoteFtpPasv,interVerType,serviceType,remarks,remoteFtpUpPath,rftpUpPathBak,rftpUpPrefix,rftpUpTime,backupKeepDays,active",
		"msisdnReceiptor": " ",
		"interComType": 1,
		"response": 0,
		"rftpBackTime": 0,
		"rftpOperPrefix": " ",
		"rftpBackPath": " ",
		"remoteFtpPwd": "22",
		"dbName": "",
		"remoteIp": " ",
		"rftpOperTime": 0,
		"rftpBackPathBak": " ",
		"rftpUpPrefix": "MONLOG",
		"remoteName": " ",
		"localPort": 0,
		"dbType": -1,
		"remoteFtpUpPath": "",
		"localIp": " ",
		"dbPsw": " ",
		"commonCfg": null,
		"interVerType": 6,
		"remoteFtpUser": "22",
		"rftpRemoteBlkPath": "",
		"rftpUpPathBak": "",
		"ftpDelBackTime": 0,
		"interType": 0,
		"interName": "2",
		"serviceType": "1,3",
		"backupKeepDays": 1,
		"syncDirection": 0,
		"remoteFtpIp": "2.2.2.2",
		"remoteFtpPasv": 1,
		"rftpBackPrefix": " ",
		"rftpOperPath": " ",
		"rftpOperPathBak": " ",
		"rftpOperSeqence": 0,
		"rftpUpSeqence": 0,
		"active": 1,
		"remotePort": 0,
		"neBlkCycle": 0,
		"rftpUpPathTmp": "",
		"remoteFtpPort": 21
	},
	{
		"recordId": 42,
		"rftpBossTime": 0,
		"rftpUpTime": 300,
		"remotePwd": " ",
		"dbUser": " ",
		"remarks": "",
		"msisdnSender": "interName,interComType,remoteFtpIp,remoteFtpPort,remoteFtpUser,remoteFtpPasv,interVerType,serviceType,remarks,remoteFtpUpPath,rftpUpPathBak,rftpUpPrefix,rftpUpTime,backupKeepDays,active",
		"msisdnReceiptor": " ",
		"interComType": 1,
		"response": 0,
		"rftpBackTime": 0,
		"rftpOperPrefix": " ",
		"rftpBackPath": " ",
		"remoteFtpPwd": "111",
		"dbName": "",
		"remoteIp": " ",
		"rftpOperTime": 0,
		"rftpBackPathBak": " ",
		"rftpUpPrefix": "MONLOG",
		"remoteName": " ",
		"localPort": 0,
		"dbType": -1,
		"remoteFtpUpPath": "",
		"localIp": " ",
		"dbPsw": " ",
		"commonCfg": null,
		"interVerType": 6,
		"remoteFtpUser": "11",
		"rftpRemoteBlkPath": "",
		"rftpUpPathBak": "",
		"ftpDelBackTime": 0,
		"interType": 0,
		"interName": "11",
		"serviceType": "3",
		"backupKeepDays": 1,
		"syncDirection": 0,
		"remoteFtpIp": "1.1.1.1",
		"remoteFtpPasv": 1,
		"rftpBackPrefix": " ",
		"rftpOperPath": " ",
		"rftpOperPathBak": " ",
		"rftpOperSeqence": 0,
		"rftpUpSeqence": 0,
		"active": 1,
		"remotePort": 0,
		"neBlkCycle": 0,
		"rftpUpPathTmp": "",
		"remoteFtpPort": 21
	}]
}